name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [deploy]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az account set --subscription fc5bc50c-7ebd-4bc4-8f0e-d1659bf195b7
            az storage blob upload-batch --account-name storagechefsbase -d '$web' -s ./production-files --subscription fc5bc50c-7ebd-4bc4-8f0e-d1659bf195b7
    
    - name: Azure logout
      run: |
            az logout